# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-13 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.EmailField(default='abc@hw.com', max_length=254),
        ),
        migrations.AddField(
            model_name='people',
            name='passwd',
            field=models.CharField(default='abc', max_length=512),
        ),
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
