# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-13 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_auto_20230413_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=18)),
                ('people', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='one.People')),
            ],
        ),
    ]
