# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-13 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_idcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcard',
            name='no',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
