# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-14 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0006_auto_20230413_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='test')),
            ],
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': '班级', 'verbose_name_plural': '班级'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生'},
        ),
    ]
