# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-04-13 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230413_1543'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('my_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
